//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace register_functionlity.DB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class AirlineRestrictionAir
    {
        public long Id { get; set; }
        public string AirlineName { get; set; }
        public string IATACode { get; set; }
        public Nullable<long> DefaultCompanyId { get; set; }
        public System.DateTime CreatedDate { get; set; }
        public bool IsDeleted { get; set; }
        public Nullable<long> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
        public Nullable<bool> IsNetfareMarkup { get; set; }
        public Nullable<bool> IsPublicMarkup { get; set; }
    
        public virtual CompanyDetail CompanyDetail { get; set; }
    }
}
