//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace register_functionlity.DB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookingReport
    {
        public long Id { get; set; }
        public string Title { get; set; }
        public string Locator { get; set; }
        public Nullable<System.DateTime> ReservationDate { get; set; }
        public Nullable<System.DateTime> DepartureDate { get; set; }
        public string Departure { get; set; }
        public string Destination { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public long DefaultCompanyId { get; set; }
        public string BillingEmail { get; set; }
        public string BillingPhone { get; set; }
        public Nullable<long> UserId { get; set; }
    
        public virtual CompanyDetail CompanyDetail { get; set; }
    }
}
