//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace register_functionlity.DB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ComapanyDomainDetail
    {
        public int Id { get; set; }
        public string DomainName { get; set; }
        public long SupplierId { get; set; }
        public long CompanyId { get; set; }
        public int ApplicationId { get; set; }
    }
}
