//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace register_functionlity.DB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CompanyDetail()
        {
            this.BookingReports = new HashSet<BookingReport>();
            this.Users = new HashSet<User>();
            this.AirlineRestrictionAirs = new HashSet<AirlineRestrictionAir>();
        }
    
        public long Id { get; set; }
        public string Name { get; set; }
        public Nullable<long> CityID { get; set; }
        public string OtherCity { get; set; }
        public Nullable<long> StateID { get; set; }
        public string OtherState { get; set; }
        public Nullable<long> CountryID { get; set; }
        public string OtherCountry { get; set; }
        public string StreetAddress { get; set; }
        public string IsActive { get; set; }
        public string WebsiteURL { get; set; }
        public string ApplicationURL { get; set; }
        public string SmtpEmailID { get; set; }
        public string EMailName { get; set; }
        public string SMTPHostName { get; set; }
        public string SmtpServerPort { get; set; }
        public string SMTPUserName { get; set; }
        public string SMTPPassword { get; set; }
        public Nullable<bool> SMTPUseSsl { get; set; }
        public string GSTRegNo { get; set; }
        public string TICORegNo { get; set; }
        public string IATANo { get; set; }
        public string PhoneNumber { get; set; }
        public Nullable<long> ParentId { get; set; }
        public Nullable<int> CompanyTypeId { get; set; }
        public string HeaderURL { get; set; }
        public string FooterURL { get; set; }
        public string WaitURL { get; set; }
        public bool Air { get; set; }
        public bool Hotel { get; set; }
        public bool CarRental { get; set; }
        public bool Enable { get; set; }
        public string Fax { get; set; }
        public string PrivacyUrl { get; set; }
        public string TermsUrl { get; set; }
        public string PostalCode { get; set; }
        public string Dk_Number { get; set; }
        public string CurrencyCode { get; set; }
        public string Location { get; set; }
        public Nullable<bool> IsApproved { get; set; }
        public string FaviconUrl { get; set; }
        public Nullable<bool> IsSandBox { get; set; }
        public Nullable<bool> IsBookingEnabled { get; set; }
        public bool Insurance { get; set; }
        public Nullable<bool> IsSandboxAir { get; set; }
        public Nullable<bool> IsSandboxCar { get; set; }
        public Nullable<bool> IsSandboxInsurance { get; set; }
        public Nullable<bool> IsBookingEnabledAir { get; set; }
        public Nullable<bool> IsBookingEnabledCar { get; set; }
        public Nullable<bool> IsBookingEnabledInsurance { get; set; }
        public Nullable<bool> CCEnableHotel { get; set; }
        public Nullable<bool> CCEnableAir { get; set; }
        public Nullable<bool> CCEnableCar { get; set; }
        public Nullable<bool> CCEnableInsurance { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookingReport> BookingReports { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AirlineRestrictionAir> AirlineRestrictionAirs { get; set; }
    }
}
