//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace register_functionlity.DB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactDetail
    {
        public int Id { get; set; }
        public long UserID { get; set; }
        public string PaymentMethod { get; set; }
        public string CreditCardNumber { get; set; }
        public string CreditCardName { get; set; }
        public string CreditCardExpDate { get; set; }
        public Nullable<int> CVV { get; set; }
        public string UserLocation { get; set; }
        public string UserStreetAddress { get; set; }
        public string UserZip { get; set; }
        public Nullable<long> UserPhone { get; set; }
        public string ContactEmail { get; set; }
    }
}
