//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace register_functionlity.DB.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class AirAdminDBEntities : DbContext
    {
        public AirAdminDBEntities()
            : base("name=AirAdminDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<ComapanyDomainDetail> ComapanyDomainDetails { get; set; }
        public virtual DbSet<CompanyDomain> CompanyDomains { get; set; }
        public virtual DbSet<BookingReport> BookingReports { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<ContactDetail> ContactDetails { get; set; }
        public virtual DbSet<DomainPaymentOptionMapping> DomainPaymentOptionMappings { get; set; }
        public virtual DbSet<PaymentOption> PaymentOptions { get; set; }
        public virtual DbSet<CompanyDetail> CompanyDetails { get; set; }
        public virtual DbSet<AirlineRestrictionAir> AirlineRestrictionAirs { get; set; }
    }
}
