//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace register_functionlity.DB.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public long Id { get; set; }
        public string UserName { get; set; }
        public long CompanyDetailId { get; set; }
        public int UserRoleId { get; set; }
        public string EmailAddress { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address { get; set; }
        public string PhoneNumber { get; set; }
        public bool IsActive { get; set; }
        public string Password { get; set; }
        public bool CanUpdatePassword { get; set; }
        public Nullable<bool> IsTempPEDResetRequest { get; set; }
        public string TempPassword { get; set; }
        public Nullable<System.DateTime> TempPasswordDateTime { get; set; }
        public Nullable<bool> IsTempPasswordExpired { get; set; }
        public string ResetPasswordCode { get; set; }
        public string Ext { get; set; }
    
        public virtual CompanyDetail CompanyDetail { get; set; }
    }
}
