//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18063
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace App.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("App.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action.
        /// </summary>
        public static string Action {
            get {
                return ResourceManager.GetString("Action", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action Required.
        /// </summary>
        public static string Action_Required {
            get {
                return ResourceManager.GetString("Action_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Project.
        /// </summary>
        public static string Add_new_project {
            get {
                return ResourceManager.GetString("Add_new_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add New Project.
        /// </summary>
        public static string Add_new_project1 {
            get {
                return ResourceManager.GetString("Add_new_project1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Additional Occupancy is required ?.
        /// </summary>
        public static string Additional_Occupancy {
            get {
                return ResourceManager.GetString("Additional_Occupancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advance Period(Days).
        /// </summary>
        public static string Advance_Period {
            get {
                return ResourceManager.GetString("Advance_Period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Engineer.
        /// </summary>
        public static string Agency_engineer {
            get {
                return ResourceManager.GetString("Agency_engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency ID.
        /// </summary>
        public static string Agency_ID {
            get {
                return ResourceManager.GetString("Agency_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency Response.
        /// </summary>
        public static string Agency_Response {
            get {
                return ResourceManager.GetString("Agency_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answers.
        /// </summary>
        public static string Answers {
            get {
                return ResourceManager.GetString("Answers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Applied.
        /// </summary>
        public static string App_Permit_Applied {
            get {
                return ResourceManager.GetString("App_Permit_Applied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Permit Received.
        /// </summary>
        public static string App_Permit_Received {
            get {
                return ResourceManager.GetString("App_Permit_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Type.
        /// </summary>
        public static string application_type {
            get {
                return ResourceManager.GetString("application_type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Applied Emergency Permit.
        /// </summary>
        public static string Applied_Emergency_Permit {
            get {
                return ResourceManager.GetString("Applied_Emergency_Permit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apply Emergency Permit.
        /// </summary>
        public static string Apply_Emergency_Permit {
            get {
                return ResourceManager.GetString("Apply_Emergency_Permit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved By.
        /// </summary>
        public static string Approved_by {
            get {
                return ResourceManager.GetString("Approved_by", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Approved On.
        /// </summary>
        public static string Approved_on {
            get {
                return ResourceManager.GetString("Approved_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Application to User.
        /// </summary>
        public static string Assign_app_to_user {
            get {
                return ResourceManager.GetString("Assign_app_to_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign RO.
        /// </summary>
        public static string Assign_RO {
            get {
                return ResourceManager.GetString("Assign_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assigned details are updated.
        /// </summary>
        public static string assignment_details {
            get {
                return ResourceManager.GetString("assignment_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Associated Agency.
        /// </summary>
        public static string Associated_agency_name {
            get {
                return ResourceManager.GetString("Associated_agency_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attachments.
        /// </summary>
        public static string Attachments {
            get {
                return ResourceManager.GetString("Attachments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Award Letter.
        /// </summary>
        public static string Award_letter {
            get {
                return ResourceManager.GetString("Award_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to login.
        /// </summary>
        public static string Back_to_login {
            get {
                return ResourceManager.GetString("Back_to_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment cannot be null in this case.
        /// </summary>
        public static string Comment_cannot_be_null_in_this_case {
            get {
                return ResourceManager.GetString("Comment_cannot_be_null_in_this_case", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comments.
        /// </summary>
        public static string Comments {
            get {
                return ResourceManager.GetString("Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Information.
        /// </summary>
        public static string Contract_information {
            get {
                return ResourceManager.GetString("Contract_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Number.
        /// </summary>
        public static string Contract_number {
            get {
                return ResourceManager.GetString("Contract_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract_number_HelpText.
        /// </summary>
        public static string Contract_number_HelpText {
            get {
                return ResourceManager.GetString("Contract_number_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract Value (QAR).
        /// </summary>
        public static string Contract_value {
            get {
                return ResourceManager.GetString("Contract_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contract_value_HelpText.
        /// </summary>
        public static string Contract_value_HelpText {
            get {
                return ResourceManager.GetString("Contract_value_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractor.
        /// </summary>
        public static string Contractor {
            get {
                return ResourceManager.GetString("Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contractors.
        /// </summary>
        public static string Contractors {
            get {
                return ResourceManager.GetString("Contractors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Either required field is empty or wrong value filled.
        /// </summary>
        public static string Coomon_validation_msg {
            get {
                return ResourceManager.GetString("Coomon_validation_msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy RO Data.
        /// </summary>
        public static string Copy_RO_Data {
            get {
                return ResourceManager.GetString("Copy_RO_Data", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string Created_on {
            get {
                return ResourceManager.GetString("Created_on", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q-PRO Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something Wrong.
        /// </summary>
        public static string dateworning {
            get {
                return ResourceManager.GetString("dateworning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DE Title.
        /// </summary>
        public static string DE_Title {
            get {
                return ResourceManager.GetString("DE_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **File Deleted Successfully**.
        /// </summary>
        public static string Deleted_Successfully {
            get {
                return ResourceManager.GetString("Deleted_Successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **File Deleted Successfully**.
        /// </summary>
        public static string Deleted_Successfully1 {
            get {
                return ResourceManager.GetString("Deleted_Successfully1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Depth(Meters).
        /// </summary>
        public static string Depth {
            get {
                return ResourceManager.GetString("Depth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter RO Description here....
        /// </summary>
        public static string desc_placeholder {
            get {
                return ResourceManager.GetString("desc_placeholder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description1 {
            get {
                return ResourceManager.GetString("Description1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Required.
        /// </summary>
        public static string Design_required {
            get {
                return ResourceManager.GetString("Design_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Required.
        /// </summary>
        public static string Design_required1 {
            get {
                return ResourceManager.GetString("Design_required1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Review No.
        /// </summary>
        public static string Design_Review_No {
            get {
                return ResourceManager.GetString("Design_Review_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Details.
        /// </summary>
        public static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Documnents required are mandatory*.
        /// </summary>
        public static string Documents_are_Mandatory {
            get {
                return ResourceManager.GetString("Documents_are_Mandatory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mandatory Documents.
        /// </summary>
        public static string Documents_Required {
            get {
                return ResourceManager.GetString("Documents_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email  ID.
        /// </summary>
        public static string Email_id {
            get {
                return ResourceManager.GetString("Email_id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email ID is required !!.
        /// </summary>
        public static string Email_is_required {
            get {
                return ResourceManager.GetString("Email_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Diagnosis.
        /// </summary>
        public static string Emergency_Diagnosis {
            get {
                return ResourceManager.GetString("Emergency_Diagnosis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency permit data not saved.
        /// </summary>
        public static string Emergencydatanotsaved {
            get {
                return ResourceManager.GetString("Emergencydatanotsaved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End.
        /// </summary>
        public static string End {
            get {
                return ResourceManager.GetString("End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        public static string End_date {
            get {
                return ResourceManager.GetString("End_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to End Date:.
        /// </summary>
        public static string End_date1 {
            get {
                return ResourceManager.GetString("End_date1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Only Numeric Value.
        /// </summary>
        public static string Ente_Only_Numerical_Value {
            get {
                return ResourceManager.GetString("Ente_Only_Numerical_Value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Comments.
        /// </summary>
        public static string Enter_Comments {
            get {
                return ResourceManager.GetString("Enter_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your details to begin.
        /// </summary>
        public static string Enter_Details {
            get {
                return ResourceManager.GetString("Enter_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Work Order No..
        /// </summary>
        public static string enter_work_order_number {
            get {
                return ResourceManager.GetString("enter_work_order_number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Your Comments.
        /// </summary>
        public static string enter_your_comments {
            get {
                return ResourceManager.GetString("enter_your_comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emergency Permit Not Updated.
        /// </summary>
        public static string EpnoteUpdated {
            get {
                return ResourceManager.GetString("EpnoteUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occured.
        /// </summary>
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Est. Road work value(QAR).
        /// </summary>
        public static string Est_Road_work_value {
            get {
                return ResourceManager.GetString("Est_Road_work_value", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend Ro Duration.
        /// </summary>
        public static string Extend_Ro_Duration {
            get {
                return ResourceManager.GetString("Extend_Ro_Duration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to **The Required Documents Extentions are pdf/doc/docx/dwg/rar/zip**.
        /// </summary>
        public static string Extensions_check {
            get {
                return ResourceManager.GetString("Extensions_check", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fax:.
        /// </summary>
        public static string Fax {
            get {
                return ResourceManager.GetString("Fax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fcc.
        /// </summary>
        public static string Fcc {
            get {
                return ResourceManager.GetString("Fcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee already Paid.
        /// </summary>
        public static string FeeexixtinDB {
            get {
                return ResourceManager.GetString("FeeexixtinDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file Format. Only  &apos;.doc&apos;, &apos;.docx&apos;,&apos;.pdf&apos;  are allowed..
        /// </summary>
        public static string File_format_error {
            get {
                return ResourceManager.GetString("File_format_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Uploaded Sucessfully.
        /// </summary>
        public static string FileUploaded_sucessfully {
            get {
                return ResourceManager.GetString("FileUploaded_sucessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please fill all mandatory fields.
        /// </summary>
        public static string filldatavalidation {
            get {
                return ResourceManager.GetString("filldatavalidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to Qatar   Permit Road Opening   and Occupancy (QPRO)  Version 2.0.
        /// </summary>
        public static string First_Slide_landpage {
            get {
                return ResourceManager.GetString("First_Slide_landpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO Permit issued by Public Works Authority to an applicant  (contractor) after approval from all utility agencies for carrying  out road works or occupy road space for specified period of time..
        /// </summary>
        public static string First_Slide_landpage_Text {
            get {
                return ResourceManager.GetString("First_Slide_landpage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Robust Validations and Analysis.
        /// </summary>
        public static string Five_Slide_landpage {
            get {
                return ResourceManager.GetString("Five_Slide_landpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are many validations at spatial and attribute data level that is placed in the new system to ensure accuracy and efficient handling of the RO permit applications. Impact analysis, Proximity analysis are performed to ensure any conflicts..
        /// </summary>
        public static string Five_Slide_landpage_text {
            get {
                return ResourceManager.GetString("Five_Slide_landpage_text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password.
        /// </summary>
        public static string Forgot_Password {
            get {
                return ResourceManager.GetString("Forgot_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Participate / Invite Agencies into RO Approval Process.
        /// </summary>
        public static string Fourth_Slide_landpage {
            get {
                return ResourceManager.GetString("Fourth_Slide_landpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any Agency that Ashghal feels should participate in a RO approval process, can be invited to be a part. On the other hand, if any agency feels it should be a part of the approval process of an RO can request to participate in the approval process..
        /// </summary>
        public static string Fourth_Slide_landpage_Text {
            get {
                return ResourceManager.GetString("Fourth_Slide_landpage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Get in touch with us .
        /// </summary>
        public static string Get_in_touch_with_us {
            get {
                return ResourceManager.GetString("Get_in_touch_with_us", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BaseMap Gallery.
        /// </summary>
        public static string GIS_BaseMap_Gallery {
            get {
                return ResourceManager.GetString("GIS_BaseMap_Gallery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overlapping with Parcel Layer... Do you want to Clip the Graphics ?.
        /// </summary>
        public static string GIS_CLIP_Msg {
            get {
                return ResourceManager.GetString("GIS_CLIP_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draw RO Location.
        /// </summary>
        public static string GIS_Draw_RO_Location {
            get {
                return ResourceManager.GetString("GIS_Draw_RO_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        public static string GIS_Draw_RO_Location_Clear {
            get {
                return ResourceManager.GetString("GIS_Draw_RO_Location_Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygon.
        /// </summary>
        public static string GIS_Draw_RO_Location_Polygon {
            get {
                return ResourceManager.GetString("GIS_Draw_RO_Location_Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string GIS_Draw_RO_Location_Save {
            get {
                return ResourceManager.GetString("GIS_Draw_RO_Location_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Cordinates.
        /// </summary>
        public static string GIS_Enter_Cordinates {
            get {
                return ResourceManager.GetString("GIS_Enter_Cordinates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Row.
        /// </summary>
        public static string GIS_Enter_Cordinates_Add_Rows {
            get {
                return ResourceManager.GetString("GIS_Enter_Cordinates_Add_Rows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeleteRow.
        /// </summary>
        public static string GIS_Enter_Cordinates_DeleteRow {
            get {
                return ResourceManager.GetString("GIS_Enter_Cordinates_DeleteRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click  to Enter Cordinates.
        /// </summary>
        public static string GIS_Enter_Cordinates_Label {
            get {
                return ResourceManager.GetString("GIS_Enter_Cordinates_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extra Fields.
        /// </summary>
        public static string GIS_Extrafields {
            get {
                return ResourceManager.GetString("GIS_Extrafields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to With in own Design Review.
        /// </summary>
        public static string GIS_GP_MSG_DR {
            get {
                return ResourceManager.GetString("GIS_GP_MSG_DR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Checking Landrow Layer Validation..
        /// </summary>
        public static string GIS_GP_MSG_LV {
            get {
                return ResourceManager.GetString("GIS_GP_MSG_LV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Outside own Design Review.
        /// </summary>
        public static string GIS_GP_MSG_NDR {
            get {
                return ResourceManager.GetString("GIS_GP_MSG_NDR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Than One RO Locations.. Select the primary RO.
        /// </summary>
        public static string GIS_GP_MSG_PL {
            get {
                return ResourceManager.GetString("GIS_GP_MSG_PL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Entered by You is Overlapping With Restricted Area..
        /// </summary>
        public static string GIS_GP_MSG_R {
            get {
                return ResourceManager.GetString("GIS_GP_MSG_R", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Graphics Entered by You is Overlapping With  RO.
        /// </summary>
        public static string GIS_GP_MSG_RO {
            get {
                return ResourceManager.GetString("GIS_GP_MSG_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intersect with own RO... Draw Again.
        /// </summary>
        public static string GIS_GP_MSG_WR {
            get {
                return ResourceManager.GetString("GIS_GP_MSG_WR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Legend.
        /// </summary>
        public static string GIS_Legend {
            get {
                return ResourceManager.GetString("GIS_Legend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run Analysis.
        /// </summary>
        public static string GIS_Phasing_Analysis {
            get {
                return ResourceManager.GetString("GIS_Phasing_Analysis", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phasing Diversion.
        /// </summary>
        public static string GIS_Phasing_Diversion {
            get {
                return ResourceManager.GetString("GIS_Phasing_Diversion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string GIS_Search_RO_Location {
            get {
                return ResourceManager.GetString("GIS_Search_RO_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Text.
        /// </summary>
        public static string GIS_Search_Text {
            get {
                return ResourceManager.GetString("GIS_Search_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Type.
        /// </summary>
        public static string GIS_Search_Type {
            get {
                return ResourceManager.GetString("GIS_Search_Type", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tools.
        /// </summary>
        public static string GIS_TOC {
            get {
                return ResourceManager.GetString("GIS_TOC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Text, DWG, SHP Files are Allowed.
        /// </summary>
        public static string GIS_Upload_Files {
            get {
                return ResourceManager.GetString("GIS_Upload_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload RO Location.
        /// </summary>
        public static string GIS_Upload_RO_Location {
            get {
                return ResourceManager.GetString("GIS_Upload_RO_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate File.
        /// </summary>
        public static string GIS_Valitdate_Img {
            get {
                return ResourceManager.GetString("GIS_Valitdate_Img", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View RO Location.
        /// </summary>
        public static string GIS_View_RO_Location {
            get {
                return ResourceManager.GetString("GIS_View_RO_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Authorization.
        /// </summary>
        public static string GIS_WorkAuthorization {
            get {
                return ResourceManager.GetString("GIS_WorkAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hide Map.
        /// </summary>
        public static string Hide_Map {
            get {
                return ResourceManager.GetString("Hide_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Emergency RO.
        /// </summary>
        public static string Invalid_Emergency_RO {
            get {
                return ResourceManager.GetString("Invalid_Emergency_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite.
        /// </summary>
        public static string invite {
            get {
                return ResourceManager.GetString("invite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invite Agency.
        /// </summary>
        public static string invite_agency {
            get {
                return ResourceManager.GetString("invite_agency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keywords.
        /// </summary>
        public static string Keywords {
            get {
                return ResourceManager.GetString("Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Landing Page.
        /// </summary>
        public static string LandingPage {
            get {
                return ResourceManager.GetString("LandingPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Map.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Days.
        /// </summary>
        public static string Max_Days {
            get {
                return ResourceManager.GetString("Max_Days", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobility.
        /// </summary>
        public static string Mobility {
            get {
                return ResourceManager.GetString("Mobility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More Site Engineer.
        /// </summary>
        public static string More_Site_Engineer {
            get {
                return ResourceManager.GetString("More_Site_Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More site engineer is populated in the list.
        /// </summary>
        public static string moresiteenggipopulate {
            get {
                return ResourceManager.GetString("moresiteenggipopulate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More than one type of RO is not allowed.
        /// </summary>
        public static string morethanselectvalidate {
            get {
                return ResourceManager.GetString("morethanselectvalidate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New User Registration.
        /// </summary>
        public static string New_User_Registration {
            get {
                return ResourceManager.GetString("New_User_Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password is required !!.
        /// </summary>
        public static string Pass_is_required {
            get {
                return ResourceManager.GetString("Pass_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pcc.
        /// </summary>
        public static string Pcc {
            get {
                return ResourceManager.GetString("Pcc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please click on the document link to upload the mandatory documents.
        /// </summary>
        public static string please_click {
            get {
                return ResourceManager.GetString("please_click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Please Comment Something or use Standard Comments*.
        /// </summary>
        public static string Please_comment_something {
            get {
                return ResourceManager.GetString("Please_comment_something", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter RO Title.
        /// </summary>
        public static string Please_Enter_RO_Title {
            get {
                return ResourceManager.GetString("Please_Enter_RO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Your Information.
        /// </summary>
        public static string Please_enter_your_information {
            get {
                return ResourceManager.GetString("Please_enter_your_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Please Fill the Date Validity*.
        /// </summary>
        public static string please_fill_the_date_validity {
            get {
                return ResourceManager.GetString("please_fill_the_date_validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Please Fill The Keywords*.
        /// </summary>
        public static string Please_fill_the_keywords {
            get {
                return ResourceManager.GetString("Please_fill_the_keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please save all steps.
        /// </summary>
        public static string please_save_all_steps {
            get {
                return ResourceManager.GetString("please_save_all_steps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select role to login.
        /// </summary>
        public static string Please_select_role_to_login {
            get {
                return ResourceManager.GetString("Please_select_role_to_login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a status.
        /// </summary>
        public static string Please_select_status {
            get {
                return ResourceManager.GetString("Please_select_status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Please Select the Status First*.
        /// </summary>
        public static string Please_Select_the_Status_First {
            get {
                return ResourceManager.GetString("Please_Select_the_Status_First", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *Please Upload The Documents Before Submit*.
        /// </summary>
        public static string Please_Upload_the_Doc {
            get {
                return ResourceManager.GetString("Please_Upload_the_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous Award Letter.
        /// </summary>
        public static string Previous_award_letter {
            get {
                return ResourceManager.GetString("Previous_award_letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string print {
            get {
                return ResourceManager.GetString("print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Comments.
        /// </summary>
        public static string Print_Comments {
            get {
                return ResourceManager.GetString("Print_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print Map.
        /// </summary>
        public static string Print_Map {
            get {
                return ResourceManager.GetString("Print_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority ID.
        /// </summary>
        public static string Priority_ID {
            get {
                return ResourceManager.GetString("Priority_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0% complete.
        /// </summary>
        public static string process_complete {
            get {
                return ResourceManager.GetString("process_complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Added Successfully Project no :.
        /// </summary>
        public static string Project_added_successfully {
            get {
                return ResourceManager.GetString("Project_added_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Date.
        /// </summary>
        public static string Project_Date {
            get {
                return ResourceManager.GetString("Project_Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project For.
        /// </summary>
        public static string Project_for {
            get {
                return ResourceManager.GetString("Project_for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Information.
        /// </summary>
        public static string Project_Information {
            get {
                return ResourceManager.GetString("Project_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Name.
        /// </summary>
        public static string Project_name {
            get {
                return ResourceManager.GetString("Project_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project No.
        /// </summary>
        public static string Project_no {
            get {
                return ResourceManager.GetString("Project_no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project status cannot be update.
        /// </summary>
        public static string Project_status_cannot_be_update {
            get {
                return ResourceManager.GetString("Project_status_cannot_be_update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project updated successfully project no :.
        /// </summary>
        public static string project_updated_successfully {
            get {
                return ResourceManager.GetString("project_updated_successfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should be alphabetic.
        /// </summary>
        public static string ProjectName_HelpText {
            get {
                return ResourceManager.GetString("ProjectName_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can be alphanumeric .
        /// </summary>
        public static string ProjectNo_HelpText {
            get {
                return ResourceManager.GetString("ProjectNo_HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Details.
        /// </summary>
        public static string Projects_details {
            get {
                return ResourceManager.GetString("Projects_details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects Information.
        /// </summary>
        public static string Projects_information {
            get {
                return ResourceManager.GetString("Projects_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q-PRO Newsletter.
        /// </summary>
        public static string Qpro_newsletter {
            get {
                return ResourceManager.GetString("Qpro_newsletter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe to the Newsletter to receive regular updates and announcements..
        /// </summary>
        public static string Qpro_newsletter_Text {
            get {
                return ResourceManager.GetString("Qpro_newsletter_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q-PRO System.
        /// </summary>
        public static string QproSystem {
            get {
                return ResourceManager.GetString("QproSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q-PRO system is an online road opening permit system designed to facilitate road opening permit.This online permitting system will replace the existing paper based procedure into an electronic web based system. This system has a central repository of the RO permitting information providing electronic RO applications and review forms.This system will drastically reduce the process from several months to few days or in some cases to few hours..
        /// </summary>
        public static string QproSystem_Text {
            get {
                return ResourceManager.GetString("QproSystem_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions.
        /// </summary>
        public static string Questions {
            get {
                return ResourceManager.GetString("Questions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter your email and to receive instructions.
        /// </summary>
        public static string Receive_Instructions {
            get {
                return ResourceManager.GetString("Receive_Instructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Received Permits.
        /// </summary>
        public static string Received_Permits {
            get {
                return ResourceManager.GetString("Received_Permits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register for Alerts.
        /// </summary>
        public static string Register_for_Alerts {
            get {
                return ResourceManager.GetString("Register_for_Alerts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On information that is important to you..
        /// </summary>
        public static string Register_for_project_Text {
            get {
                return ResourceManager.GetString("Register_for_project_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reinstatement.
        /// </summary>
        public static string Reinstatement {
            get {
                return ResourceManager.GetString("Reinstatement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember Me.
        /// </summary>
        public static string Remember_me {
            get {
                return ResourceManager.GetString("Remember_me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fee Paid successfully.
        /// </summary>
        public static string resc_addFeePayment {
            get {
                return ResourceManager.GetString("resc_addFeePayment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO ASSIGNED SUCCESSFULLY.
        /// </summary>
        public static string resc_assignedRO {
            get {
                return ResourceManager.GetString("resc_assignedRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled  successfully.
        /// </summary>
        public static string resc_Cancelled {
            get {
                return ResourceManager.GetString("resc_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO has already cancelled!.
        /// </summary>
        public static string resc_cancelledRO {
            get {
                return ResourceManager.GetString("resc_cancelledRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Droft RO Deleted Successfully.
        /// </summary>
        public static string resc_DraftDeleted {
            get {
                return ResourceManager.GetString("resc_DraftDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project contract number exists!.
        /// </summary>
        public static string resc_duplicateProjContractNo {
            get {
                return ResourceManager.GetString("resc_duplicateProjContractNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project number cannot be more than max length!.
        /// </summary>
        public static string resc_ExceedLenProjNo {
            get {
                return ResourceManager.GetString("resc_ExceedLenProjNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project No. already exist!.
        /// </summary>
        public static string resc_existsinDB {
            get {
                return ResourceManager.GetString("resc_existsinDB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no RO for revoke!.
        /// </summary>
        public static string resc_NoRevokeRO {
            get {
                return ResourceManager.GetString("resc_NoRevokeRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Such Draft RO Exist.
        /// </summary>
        public static string resc_nosuchRO {
            get {
                return ResourceManager.GetString("resc_nosuchRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already requested canceling this RO ,please make the payment first!.
        /// </summary>
        public static string resc_pendingforFee {
            get {
                return ResourceManager.GetString("resc_pendingforFee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO must be in valid state!.
        /// </summary>
        public static string resc_RevokeRO {
            get {
                return ResourceManager.GetString("resc_RevokeRO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke RO request has already been pending for approval !.
        /// </summary>
        public static string resc_RevokeROapproval {
            get {
                return ResourceManager.GetString("resc_RevokeROapproval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO has already been revoked !.
        /// </summary>
        public static string resc_RevokeROrevoked {
            get {
                return ResourceManager.GetString("resc_RevokeROrevoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Revoke request has been updated!.
        /// </summary>
        public static string resc_RevokeROupdated {
            get {
                return ResourceManager.GetString("resc_RevokeROupdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO end date is greater than defined Max RO period.
        /// </summary>
        public static string resc_ROErrorDate {
            get {
                return ResourceManager.GetString("resc_ROErrorDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Draft RO Details updated successfully.
        /// </summary>
        public static string resc_updateDraftRODetails {
            get {
                return ResourceManager.GetString("resc_updateDraftRODetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project status updated successfully.
        /// </summary>
        public static string resc_updateProjectStatus {
            get {
                return ResourceManager.GetString("resc_updateProjectStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input values !.
        /// </summary>
        public static string resc_valueError {
            get {
                return ResourceManager.GetString("resc_valueError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        public static string Reset1 {
            get {
                return ResourceManager.GetString("Reset1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Password.
        /// </summary>
        public static string Retrieve_Password {
            get {
                return ResourceManager.GetString("Retrieve_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrieve Password.
        /// </summary>
        public static string Retrieve_Password1 {
            get {
                return ResourceManager.GetString("Retrieve_Password1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Commnets.
        /// </summary>
        public static string Review_Commnets {
            get {
                return ResourceManager.GetString("Review_Commnets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Emergency RO Submission.
        /// </summary>
        public static string Review_Emergency_RO_Submission {
            get {
                return ResourceManager.GetString("Review_Emergency_RO_Submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Submission.
        /// </summary>
        public static string Review_Submission {
            get {
                return ResourceManager.GetString("Review_Submission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO Application No.
        /// </summary>
        public static string RO_Application_No {
            get {
                return ResourceManager.GetString("RO_Application_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ro Details.
        /// </summary>
        public static string Ro_Details {
            get {
                return ResourceManager.GetString("Ro_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ro Extension Request.
        /// </summary>
        public static string Ro_Extension_Request {
            get {
                return ResourceManager.GetString("Ro_Extension_Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO Information.
        /// </summary>
        public static string RO_Information {
            get {
                return ResourceManager.GetString("RO_Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO Title.
        /// </summary>
        public static string RO_Title {
            get {
                return ResourceManager.GetString("RO_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO Validation.
        /// </summary>
        public static string RO_Validation {
            get {
                return ResourceManager.GetString("RO_Validation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Road Work.
        /// </summary>
        public static string Road_Work {
            get {
                return ResourceManager.GetString("Road_Work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Agency User(Agency Administrator - Ashghal - Roads).
        /// </summary>
        public static string Role_1 {
            get {
                return ResourceManager.GetString("Role_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Role will have Apply privileges only.
        /// </summary>
        public static string Role_1_Text {
            get {
                return ResourceManager.GetString("Role_1_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committee User(Consultant Administrator - Road Inspection Committee).
        /// </summary>
        public static string Role_2 {
            get {
                return ResourceManager.GetString("Role_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This Role will have Review and Approve privileges only..
        /// </summary>
        public static string Role_2_Text {
            get {
                return ResourceManager.GetString("Role_2_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committee User(Committee Administrator - CRA - Consortium Committee).
        /// </summary>
        public static string Role_3 {
            get {
                return ResourceManager.GetString("Role_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Committee User (Agency Administrator - Road Occupancy Committee).
        /// </summary>
        public static string Role_4 {
            get {
                return ResourceManager.GetString("Role_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input values!.
        /// </summary>
        public static string saveerror {
            get {
                return ResourceManager.GetString("saveerror", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application Saved Successfully. RO no is.
        /// </summary>
        public static string savesuccessfully {
            get {
                return ResourceManager.GetString("savesuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q-PRO System.
        /// </summary>
        public static string Second_Slide_landpage {
            get {
                return ResourceManager.GetString("Second_Slide_landpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Q-PRO system is an online road opening permit system designed to facilitate road opening permit.This online permitting system will replace the existing paper based procedure into an electronic web based system. This system has a central repository of the RO permitting information providing electronic RO applications and  review forms.This system will drastically reduce the process from several months to few days or in some cases to few hours..
        /// </summary>
        public static string Second_Slide_landpage_Text {
            get {
                return ResourceManager.GetString("Second_Slide_landpage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Contractor.
        /// </summary>
        public static string Select_Contractor {
            get {
                return ResourceManager.GetString("Select_Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Role.
        /// </summary>
        public static string Select_role {
            get {
                return ResourceManager.GetString("Select_role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type of Work.
        /// </summary>
        public static string Select_type_of_work {
            get {
                return ResourceManager.GetString("Select_type_of_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Type of Work.
        /// </summary>
        public static string Select_type_of_work1 {
            get {
                return ResourceManager.GetString("Select_type_of_work1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Work.
        /// </summary>
        public static string Select_work {
            get {
                return ResourceManager.GetString("Select_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self Contractor.
        /// </summary>
        public static string Self_Contractor {
            get {
                return ResourceManager.GetString("Self_Contractor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Me !.
        /// </summary>
        public static string Send_Me {
            get {
                return ResourceManager.GetString("Send_Me", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Keywords.
        /// </summary>
        public static string Set_Keywords {
            get {
                return ResourceManager.GetString("Set_Keywords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set Validity.
        /// </summary>
        public static string Set_Validity {
            get {
                return ResourceManager.GetString("Set_Validity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Map.
        /// </summary>
        public static string Show_Map {
            get {
                return ResourceManager.GetString("Show_Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site can be cleared until regular RO is obtained ?.
        /// </summary>
        public static string Site_Cleared {
            get {
                return ResourceManager.GetString("Site_Cleared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Site Engineer.
        /// </summary>
        public static string Site_Engineer {
            get {
                return ResourceManager.GetString("Site_Engineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Comment List.
        /// </summary>
        public static string Standard_Comment_List {
            get {
                return ResourceManager.GetString("Standard_Comment_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard Comments.
        /// </summary>
        public static string Standard_Comments {
            get {
                return ResourceManager.GetString("Standard_Comments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Start_date {
            get {
                return ResourceManager.GetString("Start_date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For the selected type of RO, advance days required for RO Application to be submitted are Ro Priority Advance Period(Days).
        /// </summary>
        public static string start_date_information {
            get {
                return ResourceManager.GetString("start_date_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Date.
        /// </summary>
        public static string Start_date1 {
            get {
                return ResourceManager.GetString("Start_date1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        public static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Approval.
        /// </summary>
        public static string Submit_Approval {
            get {
                return ResourceManager.GetString("Submit_Approval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Comment.
        /// </summary>
        public static string Submit_Comment {
            get {
                return ResourceManager.GetString("Submit_Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit Response.
        /// </summary>
        public static string Submit_Response {
            get {
                return ResourceManager.GetString("Submit_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Support.
        /// </summary>
        public static string Support {
            get {
                return ResourceManager.GetString("Support", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RO Validation / Review Detail.
        /// </summary>
        public static string tab_name {
            get {
                return ResourceManager.GetString("tab_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telephone.
        /// </summary>
        public static string Telephone {
            get {
                return ResourceManager.GetString("Telephone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to *The following extension of the file name is not valid for the selected Keyword*.
        /// </summary>
        public static string The_Following_Extension_File_Name {
            get {
                return ResourceManager.GetString("The_Following_Extension_File_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phasing and Scheduling of RO Permits.
        /// </summary>
        public static string Third_Slide_landpage {
            get {
                return ResourceManager.GetString("Third_Slide_landpage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New system allows a contractor to break the RO locations into many phases for the convenience of scheduling the work on each phase separately. This will help in minimal traffic diversion/disruptions..
        /// </summary>
        public static string Third_Slide_landpage_Text {
            get {
                return ResourceManager.GetString("Third_Slide_landpage_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total Uploaded.
        /// </summary>
        public static string Total_Uploaded {
            get {
                return ResourceManager.GetString("Total_Uploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trafic Diversion Plan Reference.
        /// </summary>
        public static string Trafic_Diversion_Plan_Reference {
            get {
                return ResourceManager.GetString("Trafic_Diversion_Plan_Reference", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of RO.
        /// </summary>
        public static string Type_f_RO {
            get {
                return ResourceManager.GetString("Type_f_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of DE.
        /// </summary>
        public static string Type_of_DE {
            get {
                return ResourceManager.GetString("Type_of_DE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of RO.
        /// </summary>
        public static string Type_of_ro {
            get {
                return ResourceManager.GetString("Type_of_ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of RO.
        /// </summary>
        public static string Type_of_ro1 {
            get {
                return ResourceManager.GetString("Type_of_ro1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type of Work.
        /// </summary>
        public static string Type_of_work {
            get {
                return ResourceManager.GetString("Type_of_work", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Project.
        /// </summary>
        public static string update_project {
            get {
                return ResourceManager.GetString("update_project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Doc.
        /// </summary>
        public static string Upload_Doc {
            get {
                return ResourceManager.GetString("Upload_Doc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Documents.
        /// </summary>
        public static string Upload_Document {
            get {
                return ResourceManager.GetString("Upload_Document", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Documents.
        /// </summary>
        public static string Upload_Documents {
            get {
                return ResourceManager.GetString("Upload_Documents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valid Emergency RO.
        /// </summary>
        public static string Valid_Emergenc_RO {
            get {
                return ResourceManager.GetString("Valid_Emergenc_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validate RO.
        /// </summary>
        public static string Validate_RO {
            get {
                return ResourceManager.GetString("Validate_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select an agency First.
        /// </summary>
        public static string validationinviteancy {
            get {
                return ResourceManager.GetString("validationinviteancy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validity upto.
        /// </summary>
        public static string Validity_upto {
            get {
                return ResourceManager.GetString("Validity_upto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View RO Location.
        /// </summary>
        public static string View_RO_Location {
            get {
                return ResourceManager.GetString("View_RO_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Who Can apply for RO permit?.
        /// </summary>
        public static string WhoCanApplyForROPermit {
            get {
                return ResourceManager.GetString("WhoCanApplyForROPermit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone who is occupying or cut the asphalt or undertake excavation work in part or full of right way..
        /// </summary>
        public static string WhoCanApplyForROPermit_Text_Li_1 {
            get {
                return ResourceManager.GetString("WhoCanApplyForROPermit_Text_Li_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anyone who plan for diversions in major or minor.
        /// </summary>
        public static string WhoCanApplyForROPermit_Text_Li_2 {
            get {
                return ResourceManager.GetString("WhoCanApplyForROPermit_Text_Li_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Order No..
        /// </summary>
        public static string Work_Order_No {
            get {
                return ResourceManager.GetString("Work_Order_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Type Details.
        /// </summary>
        public static string Work_Type_Details {
            get {
                return ResourceManager.GetString("Work_Type_Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Work Type ID.
        /// </summary>
        public static string Work_Type_ID {
            get {
                return ResourceManager.GetString("Work_Type_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
